#!/usr/bin/python3

import sys

cOption = True
wOption = True
lOption = True
mOption = False

optionsFound = False

files = []
for i in range(1,len(sys.argv)):
	if sys.argv[i][0] != "-":
		files.append(sys.argv[i])
	else:
		#found some options
		if not optionsFound:
			cOption = False
			wOption = False
			lOption = False
			optionsFound = True

		if "l" in sys.argv[i]: 
			#sys.argv[i] is an option string
			lOption = True
		if "c" in sys.argv[i]:
			cOption = True
		if "w" in sys.argv[i]:
			wOption = True
		if "m" in sys.argv[i]:
			mOption = True

if len(files) == 0:
	lineCount = 0
	wordCount = 0
	charCount = 0
	byteCount = 0
	for line in sys.stdin:
		lineCount +=1
		words = line.split()
		charCount +=len(line)
		byteCount +=len(line)
		for eachword in words:
			wordCount +=1
	
	if lOption == True: 
		print("%3d"%lineCount,end=" ")
	if wOption == True:
		print("%3d"%wordCount,end=" ")
	if mOption == True:
		print("%3d"%charCount,end=" ")
	if cOption == True:
		print("%3d"%byteCount,end=" ")		
	print()



for eachFile in files:
	aFile= open(eachFile, "r")
	lineCount = 0
	wordCount = 0
	charCount = 0
	byteCount = 0
	for line in aFile:
		lineCount +=1
		words = line.split()
		charCount +=len(line)
		byteCount +=len(line)
		for eachword in words:
			wordCount +=1
		
		
	if lOption == True: 
		print("%3d"%lineCount,end=" ")
	if wOption == True:
		print("%3d"%wordCount,end=" ")
	if mOption == True:
		print("%3d"%charCount,end=" ")
	if cOption == True:
		print("%3d"%byteCount,end=" ")
	print(eachFile)

